/**
 * Pre-compile the JSON-Schema validators into plain JavaScript (Ajv "standalone" mode).
 * Why: compiling at runtime needs eval/new Function, which the unit server's Content-Security-Policy forbids.
 * Run after editing anything in config/schema/:  npm run gen:validators
 */
import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dirname, '../../../config/schema');
const ajv = new Ajv({ allErrors: true, code: { source: true, esm: true } });
const names = ['threats', 'effectors', 'doctrine', 'training'] as const;
for (const n of names) ajv.addSchema(JSON.parse(readFileSync(join(root, `${n}.schema.json`), 'utf8')), n);
let code = standaloneCode(ajv, Object.fromEntries(names.map((n) => [n, n])));
// Make the output dependency-free ES module code (Ajv emits require() for two tiny runtime helpers).
const HELPERS: Record<string, string> = {
  'ajv/dist/runtime/ucs2length': '((s) => Array.from(s).length)',
  'ajv/dist/runtime/equal': '((a, b) => JSON.stringify(a) === JSON.stringify(b))',
};
code = code.replace(/require\("([^"]+)"\)(?:\.default)?/g, (_m, mod) => { if (!HELPERS[mod]) throw new Error(`Unexpected runtime helper ${mod}`); return HELPERS[mod]; });
if (/require\(/.test(code)) throw new Error('Generated validators still contain require()');
const out = join(import.meta.dirname, '../src/generated/validators.js');
const next = '// GENERATED by packages/engine/scripts/gen-validators.ts from config/schema/*.json. Do not edit by hand.\n' + code;
const check = process.argv.includes('--check');
if (check) {
  if (readFileSync(out, 'utf8') !== next) { console.error('✗ src/generated/validators.js is out of date. Run: npm run gen:validators'); process.exit(1); }
  console.log('✓ Generated validators are up to date');
} else { writeFileSync(out, next); console.log('✓ Wrote', out); }
